# Generated by Django 4.2.9 on 2026-05-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sede_y_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
