# Generated by Django 4.2.9 on 2026-05-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        ('ventas', '0002_venta_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='bodegas.bodega'),
        ),
    ]
