# Generated by Django 4.2.9 on 2026-05-14 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_sede_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Devengado', 'Devengado'), ('Deduccion', 'Deducción')], max_length=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='0 si es valor fijo', max_digits=6)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'db_table': 'conceptos_nomina',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=5)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Fijo', 'Término Fijo'), ('Obra_labor', 'Obra y Labor'), ('Prestacion', 'Prestación de Servicios'), ('Aprendizaje', 'Contrato de Aprendizaje')], default='Indefinido', max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Vacaciones', 'En Vacaciones'), ('Licencia', 'En Licencia')], default='Activo', max_length=12)),
                ('banco', models.CharField(blank=True, max_length=80)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('Ahorros', 'Cuenta de Ahorros'), ('Corriente', 'Cuenta Corriente')], max_length=10)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_creados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='users.sede')),
            ],
            options={
                'verbose_name': 'Empleado',
                'db_table': 'empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Aprobada', 'Aprobada'), ('Pagada', 'Pagada')], default='Borrador', max_length=10)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_nomina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'db_table': 'periodos_nomina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LineaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dias_trabajados', models.IntegerField(default=30)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('salud', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='nomina.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nomina.periodonomina')),
            ],
            options={
                'verbose_name': 'Línea de Nómina',
                'db_table': 'lineas_nomina',
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
