# Generated by Django 4.2.9 on 2026-04-27 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Devengado', 'Devengado'), ('Deduccion', 'Deducción')], max_length=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='0 si es valor fijo', max_digits=6)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'db_table': 'conceptos_nomina',
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Aprobada', 'Aprobada'), ('Pagada', 'Pagada')], default='Borrador', max_length=10)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_nomina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'db_table': 'periodos_nomina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LineaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dias_trabajados', models.IntegerField(default=30)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('salud', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nomina.periodonomina')),
            ],
            options={
                'verbose_name': 'Línea de Nómina',
                'db_table': 'lineas_nomina',
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
