# Generated by Django 4.2.9 on 2026-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(default='901334172', max_length=20)),
                ('digito_verificacion', models.CharField(default='0', max_length=1)),
                ('razon_social', models.CharField(default='SUMINISTROS DACAR S.A.S.', max_length=250)),
                ('nombre_comercial', models.CharField(default='VOLCANO ASADORES', max_length=250)),
                ('direccion', models.TextField(default='CR 17 G # 25 – 78')),
                ('ciudad', models.CharField(default='Cali', max_length=100)),
                ('departamento', models.CharField(default='Valle del Cauca', max_length=100)),
                ('telefono', models.CharField(default='316 691 4910', max_length=25)),
                ('telefono2', models.CharField(default='312 780 1986', max_length=25)),
                ('email', models.EmailField(default='suministrosdacar@gmail.com', max_length=254)),
                ('email_notificaciones', models.EmailField(default='chicaizapipe@gmail.com', help_text='Email desde donde se envían las facturas', max_length=254)),
                ('ciiu', models.CharField(default='4659', max_length=10)),
                ('regimen', models.CharField(default='Responsable de IVA', max_length=50)),
                ('responsabilidades', models.CharField(default='07-Retención en la fuente, 09-Retención IVA, 48-IVA, 52-Facturador electrónico', max_length=200)),
                ('agente_retenedor', models.BooleanField(default=True)),
                ('gran_contribuyente', models.BooleanField(default=False)),
                ('prefijo_factura', models.CharField(default='FACT', max_length=10)),
                ('resolucion_numero', models.CharField(blank=True, help_text='Número de resolución DIAN — se llena cuando esté disponible', max_length=50)),
                ('resolucion_fecha', models.DateField(blank=True, null=True)),
                ('resolucion_vigencia', models.DateField(blank=True, null=True)),
                ('rango_desde', models.PositiveIntegerField(default=1)),
                ('rango_hasta', models.PositiveIntegerField(default=1000)),
                ('consecutivo_actual', models.PositiveIntegerField(default=1)),
                ('iva_default', models.DecimalField(decimal_places=2, default=19.0, help_text='Tarifa IVA por defecto (%)', max_digits=5)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa para facturas', null=True, upload_to='configuracion/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'db_table': 'configuracion_empresa',
            },
        ),
        migrations.CreateModel(
            name='TarifaRetefuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('COMPRAS', 'Compras generales'), ('SERVICIOS', 'Servicios generales'), ('HONORARIOS', 'Honorarios'), ('ARRENDAMIENTO', 'Arrendamiento'), ('TRANSPORTE', 'Transporte de carga'), ('OTROS', 'Otros')], max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tarifa_porcentaje', models.DecimalField(decimal_places=2, help_text='Tarifa en porcentaje (%)', max_digits=5)),
                ('cuantia_minima', models.DecimalField(decimal_places=2, help_text='Valor mínimo de la factura para aplicar retención', max_digits=14)),
                ('uvt_referencia', models.IntegerField(default=2025, help_text='Año fiscal de referencia')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa Retefuente',
                'db_table': 'tarifas_retefuente',
            },
        ),
        migrations.CreateModel(
            name='TarifaReteICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('ciiu_desde', models.CharField(blank=True, help_text='Código CIIU inicio del rango', max_length=10)),
                ('ciiu_hasta', models.CharField(blank=True, help_text='Código CIIU fin del rango', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('tarifa_por_mil', models.DecimalField(decimal_places=3, help_text='Tarifa en por mil (‰)', max_digits=6)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa ReteICA',
                'db_table': 'tarifas_reteica',
                'ordering': ['ciudad', 'ciiu_desde'],
            },
        ),
    ]
