# Generated by Django 4.2.9 on 2026-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='fecha_cierre_contable',
            field=models.DateField(blank=True, help_text='No se permiten transacciones anteriores o iguales a esta fecha', null=True),
        ),
    ]
