# Generated by Django 4.2.9 on 2026-07-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_detallenotacredito'),
        ('clientes', '0002_alter_cliente_options_remove_cliente_nombre_and_more'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogopublico',
            name='categoria_display',
            field=models.CharField(blank=True, help_text='Categoría a mostrar en el portal. Si está vacía, se usa la del producto.', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogopublico',
            name='descripcion_publica',
            field=models.TextField(blank=True, help_text='Descripción comercial para mostrar al cliente. Si está vacía, se usa la del producto.'),
        ),
        migrations.AlterField(
            model_name='catalogopublico',
            name='imagen_publica',
            field=models.ImageField(blank=True, help_text='Imagen para el portal. Si está vacía, se usa la imagen del producto.', null=True, upload_to='marketplace/'),
        ),
        migrations.AlterField(
            model_name='catalogopublico',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición en el catálogo (menor = primero).'),
        ),
        migrations.AlterField(
            model_name='catalogopublico',
            name='precio_publico',
            field=models.DecimalField(decimal_places=2, help_text='Precio de lista en el portal. Si es 0, se usa el precio_venta del producto.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='catalogopublico',
            name='stock_maximo_pedido',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cantidad máxima por pedido. 0 = sin límite.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='cliente_erp',
            field=models.ForeignKey(blank=True, help_text='Cliente del ERP vinculado por NIT (si existe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_online', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='cliente_nit',
            field=models.CharField(blank=True, help_text='NIT/CC del cliente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura generada al aprobar el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_online_origen', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones del cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='token',
            field=models.CharField(editable=False, help_text='Token único para que el cliente consulte el estado del pedido sin login.', max_length=64, unique=True),
        ),
    ]
