# Generated by Django 4.2.9 on 2026-05-08 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_alter_cliente_options_remove_cliente_nombre_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('prefijo', models.CharField(default='FACT', max_length=10)),
                ('numero_completo', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('condicion_pago', models.CharField(choices=[('Contado', 'Contado'), ('15_dias', 'Crédito 15 días'), ('30_dias', 'Crédito 30 días'), ('60_dias', 'Crédito 60 días'), ('90_dias', 'Crédito 90 días')], default='Contado', max_length=15)),
                ('medio_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Tarjeta Débito'), ('Credito', 'Tarjeta Crédito'), ('Transferencia', 'Transferencia Bancaria'), ('ADDI', 'ADDI'), ('Distecredito', 'Distecredito'), ('Cheque', 'Cheque'), ('Otro', 'Otro')], default='Efectivo', max_length=15)),
                ('concepto_retefuente', models.CharField(blank=True, choices=[('COMPRAS', 'Compras generales (2.5%)'), ('SERVICIOS', 'Servicios (4%)'), ('HONORARIOS', 'Honorarios (11%)'), ('ARRENDAMIENTO', 'Arrendamiento (3.5%)'), ('TRANSPORTE', 'Transporte (1%)'), ('OTROS', 'Otros (2.5%)')], default='COMPRAS', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_iva_0', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_iva_5', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_iva_19', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_excluida', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_iva_5', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_iva_19', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('retefuente_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_retefuente', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reteiva_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_reteiva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reteica_pct', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('valor_reteica', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Emitida', 'Emitida'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('Anulada', 'Anulada')], default='Borrador', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('cufe', models.CharField(blank=True, help_text='Código único DIAN — se llena al conectar con la DIAN', max_length=200)),
                ('qr_url', models.TextField(blank=True)),
                ('fecha_emision_ts', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'db_table': 'facturas',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('numero_completo', models.CharField(editable=False, max_length=20, unique=True)),
                ('motivo', models.CharField(choices=[('DEVOLUCION', 'Devolución de mercancía'), ('DESCUENTO', 'Descuento comercial'), ('ANULACION', 'Anulación de factura'), ('PRECIO', 'Ajuste de precio'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('factura_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Nota Crédito',
                'db_table': 'notas_credito',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('es_obsequio', models.BooleanField(default=False, help_text='Descuento 100% — ítem aparece como obsequio en la factura')),
                ('iva_tipo', models.CharField(choices=[('0', 'Exento (0%)'), ('5', 'IVA 5%'), ('19', 'IVA 19%'), ('EXCLUIDO', 'Excluido de IVA')], default='19', max_length=10)),
                ('valor_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_iva_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_factura', to='productos.producto')),
            ],
            options={
                'db_table': 'factura_detalles',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
