# Generated by Django 4.2.9 on 2026-05-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='es_obsequio',
            field=models.BooleanField(default=False, help_text='Descuento 100% — ítem aparece como obsequio en la factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cufe',
            field=models.CharField(blank=True, help_text='Código único DIAN — se llena al conectar con la DIAN', max_length=200),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
