# Generated by Django 4.2.9 on 2026-05-12 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_detallefactura_es_obsequio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
