# Generated by Django 4.2.9 on 2026-05-12 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0003_alter_factura_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
