# Generated by Django 4.2.9 on 2026-05-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_bodega_factura_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='requiere_envio',
            field=models.BooleanField(default=False, help_text='Indica si esta factura debe pasar al módulo de entregas'),
        ),
    ]
