# Generated by Django 4.2.9 on 2026-04-19 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('transportista', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Tránsito', 'En Tránsito'), ('Entregada', 'Entregada'), ('Fallida', 'Fallida')], default='Pendiente', max_length=15)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entregada', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'db_table': 'entregas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
