# Generated by Django 4.2.9 on 2026-05-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_nombre_and_more'),
        ('facturacion', '0004_factura_bodega_factura_vendedor'),
        ('productos', '0003_alter_producto_iva_incluido'),
        ('bodegas', '0001_initial'),
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrantes', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salientes', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='metodo_envio',
            field=models.CharField(choices=[('Propio', 'Vehículo Propio'), ('Transportadora', 'Transportadora Externa')], default='Propio', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entrega',
            name='tipo_entrega',
            field=models.CharField(choices=[('Venta', 'Despacho de Venta'), ('Traslado', 'Traslado entre Bodegas')], default='Venta', max_length=15),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='transportista',
            field=models.CharField(blank=True, help_text='Nombre del conductor o de la empresa externa (ej. Envia, Inter Rapidisimo)', max_length=150),
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entregas.entrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'db_table': 'entrega_detalles',
            },
        ),
    ]
