# Generated by Django 4.2.9 on 2026-05-13 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_alter_producto_iva_incluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0004_factura_bodega_factura_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto_terminado', models.OneToOneField(limit_choices_to={'tipo_inventario': 'TERMINADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'db_table': 'produccion_recetas',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('cantidad_a_fabricar', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En_Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('factura_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='facturacion.factura')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.receta')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'db_table': 'produccion_ordenes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('producto_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_recetas', to='productos.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='produccion.receta')),
            ],
            options={
                'db_table': 'produccion_ingredientes',
                'unique_together': {('receta', 'producto_materia')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.DecimalField(decimal_places=3, help_text='Calculada: receta * cantidad_a_fabricar', max_digits=12)),
                ('cantidad_real', models.DecimalField(decimal_places=3, default=0, help_text='Lo que el operario dice que gastó realmente', max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.ordenproduccion')),
                ('producto_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_produccion', to='productos.producto')),
            ],
            options={
                'db_table': 'produccion_consumos',
                'unique_together': {('orden', 'producto_materia')},
            },
        ),
    ]
