# Generated by Django 4.2.9 on 2026-05-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='bodega',
            field=models.ForeignKey(blank=True, help_text='De dónde sale la materia prima y adónde entra el terminado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='bodegas.bodega'),
        ),
    ]
