# Generated by Django 4.2.9 on 2026-05-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        ('movimientos', '0002_movimiento_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bodegas.bodega'),
        ),
    ]
