# Generated by Django 4.2.9 on 2026-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_movimiento_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='saldo_cantidad',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Saldo de cantidad tras el movimiento', max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='saldo_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo valorizado tras el movimiento', max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario en este movimiento', max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
