# Generated by Django 4.2.9 on 2026-05-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_iva_incluido_y_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='iva_incluido',
            field=models.BooleanField(default=False, help_text='Si está activo, el precio de venta ya incluye el IVA. Al facturar se discrimina automáticamente la base y el IVA.'),
        ),
    ]
