# Generated by Django 4.2.9 on 2026-05-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_iva_incluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código EAN o UPC', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='controla_vencimiento',
            field=models.BooleanField(default=False, help_text='Activar para productos perecederos (carnes, condimentos) que requieren Lote y Fecha de Vencimiento.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
