# Generated by Django 4.2.9 on 2026-05-14 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_codigo_barras_producto_controla_vencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('stock_disponible', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Por Vencer', 'Por Vencer (<= 30 días)'), ('Vencido', 'Vencido'), ('Agotado', 'Agotado')], default='Vigente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto')),
            ],
            options={
                'db_table': 'lotes',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('producto', 'numero_lote')},
            },
        ),
    ]
