# Generated by Django 4.2.9 on 2026-07-10 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0006_stock_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=14),
        ),
        migrations.CreateModel(
            name='AuditoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(max_length=100)),
                ('valor_nuevo', models.CharField(max_length=100)),
                ('motivo', models.CharField(blank=True, default='Modificado desde panel administrativo', max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
