# Generated by Django 4.2.9 on 2026-04-27 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=16)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('Anulada', 'Anulada')], default='Pendiente', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp', to='compras.compra')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cxp', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'db_table': 'cuentas_por_pagar',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='PagoCXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], default='Transferencia', max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cxp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cxp.cuentaporpagar')),
            ],
            options={
                'db_table': 'pagos_cxp',
                'ordering': ['-fecha'],
            },
        ),
    ]
