# Generated by Django 4.2.9 on 2026-04-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('tipo', models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Corporativo', 'Corporativo')], default='Persona Natural', max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
