# Generated by Django 4.2.9 on 2026-05-01 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razon_social'], 'verbose_name': 'Cliente'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='agente_retenedor',
            field=models.BooleanField(default=False, help_text='Si aplica retenciones al pagar'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='autoretenedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciiu',
            field=models.CharField(blank=True, help_text='Código CIIU de actividad económica', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(blank=True, help_text='Solo para NIT', max_length=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gran_contribuyente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Colombia', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_tributario',
            field=models.CharField(choices=[('RESPONSABLE_IVA', 'Responsable de IVA'), ('NO_RESPONSABLE', 'No Responsable de IVA'), ('REGIMEN_SIMPLE', 'Régimen Simple de Tributación'), ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente'), ('ESPECIAL', 'Entidad sin ánimo de lucro'), ('PERSONA_NATURAL', 'Persona Natural no comerciante')], default='RESPONSABLE_IVA', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsable_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('NIT_EXTRAN', 'NIT Extranjero'), ('RUT', 'RUT')], default='NIT', max_length=12),
        ),
    ]
