# Generated by Django 4.2.9 on 2026-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_compra_cantidad_remove_compra_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='condicion_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('15_dias', '15 días'), ('30_dias', '30 días'), ('45_dias', '45 días'), ('60_dias', '60 días'), ('90_dias', '90 días')], default='Contado', max_length=15),
        ),
        migrations.AddField(
            model_name='compra',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_vencimiento_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
