# Generated by Django 4.2.9 on 2026-06-10 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0003_compra_condicion_pago_compra_dias_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número de nota crédito del proveedor', max_length=50)),
                ('motivo', models.CharField(choices=[('DEVOLUCION', 'Devolución de mercancía'), ('DESCUENTO', 'Descuento comercial'), ('ANULACION', 'Anulación de orden'), ('PRECIO', 'Ajuste de precio'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compra_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='compras.compra')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Crédito Proveedor',
                'db_table': 'notas_credito_proveedor',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=16)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_aplicadas', to='compras.detallecompra')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.notacreditoproveedor')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'db_table': 'nota_credito_proveedor_detalles',
            },
        ),
    ]
