# Generated by Django 4.2.16 on 2026-06-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        ('compras', '0004_notacreditoproveedor_detallenotacreditoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, help_text='Bodega donde ingresará la mercadería', null=True, on_delete=django.db.models.deletion.PROTECT, to='bodegas.bodega'),
        ),
    ]
