# Generated by Django 4.2.16 on 2026-06-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compra_bodega_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_esperada_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares Estadounidenses')], default='COP', max_length=5),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
    ]
