# Generated by Django 4.2.9 on 2026-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_campos_tributarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=150),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='regimen_tributario',
            field=models.CharField(choices=[('RESPONSABLE_IVA', 'Responsable de IVA'), ('NO_RESPONSABLE', 'No Responsable de IVA'), ('REGIMEN_SIMPLE', 'Régimen Simple de Tributación'), ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente'), ('ESPECIAL', 'Entidad sin ánimo de lucro')], default='RESPONSABLE_IVA', max_length=20),
        ),
    ]
